### PR TITLE
Run helper as D-BUS service

### PR DESCRIPTION
**Pull request by dmitry-s93**
No more need to enter a password when starting the application

### CODE REVIEW

**Comment by rottenpants466** [comment]
Nice :) For me it's not that anoying since i don't open the app frequently, but it's a good improvement.

Awesome work!

**Comment by dmitry-s93** [comment]
> Edit: not related but when you mean that the app requires the ec_sys module are you refering to this?
> https://github.com/BeardOverflow/msi-ec

No. The ec_sys module which is enabled by the command "modprobe ec_sys write_support=1"

**Comment by rottenpants466** [comment]
Interesting, i actually instaled those drivers from BeardOverflow and my battery threshold started working, without enabling the modprobe ec_sys write_support=1 command

**Comment by rottenpants466** [comment]
In my case, before installing the BeardOverflow drivers, the only thing that didn't work was the battery threshold, everything else was working.

**Comment by dmitry-s93** [comment]
The EC may have contained an initial value not recognized by MControlCenter. It would be interesting to see a dump when the battery threshold did not work.

**Comment by rottenpants466** [comment]
Can you tell me how to create that dump? using what commands on the terminal? newby here :|

I will try to boot a clean installation and also reset the bios

**Comment by dmitry-s93** [comment]
> Can you tell me how to create that dump? using what commands on the terminal?

Execute command "sudo hexdump -C /sys/kernel/debug/ec/ec0/io"

If you can reproduce the problem, please create a new issue

**Comment by rottenpants466** [comment]
Yep you were right it works without those drivers, i made a clean installation on a seperate partition and the only thing i did was activating the ec_sys module.

Sorry for the confusion

**Comment by dmitry-s93** [comment]
> the only thing i did was activating the ec_sys module

Have you activated the ec_sys module manually? Did the auto enable module not work?

**Comment by rottenpants466** [comment]
I had to activate the module manually in the terminal.

**Comment by dmitry-s93** [comment]
Without the module, none of the functions will work.  What happens if you do not activate manually?

**Comment by rottenpants466** [comment]
If i don't enable the module in the terminal the only thing that doesn't work is the battery threshold feature. 

I see that you merged this pr, maybe the next version of the app will fix it

**Comment by dmitry-s93** [comment]
Not sure if this will be fixed in the new version.  Can you describe in more detail?  What happens on the application form if you do not activate the module manually? The rest of the settings can be changed and are they successfully applied?

It is possible that ec_sys is in read-only mode.

**Comment by rottenpants466** [comment]
[Vid.zip](https://github.com/dmitry-s93/MControlCenter/files/9777926/Vid.zip)

I uploaded a video.

Clean install and the app works without activating the ec module in the terminal.

**Pull request merged**
