### PR TITLE
Add mcontrolcenter-bin PKGBUILD 

### PR DESCRIPTION
**Pull request by JordanViknar**
Hello. Thank you for this project, I was waiting for quite a long time to see someone make a control center application for MSI laptops like mine. (By the way, your application only supports it partially, it's an MSI GE63 RAIDER RGB 8RE, I'll have to remember to make an issue about it.)

I personally use Arch Linux, and I wasn't really satisfied with the idea of using an installation script when we have the entire Arch Build System available.
As such, in order for Arch(-based) users to easily download your application, I've made a PKGBUILD file that, when ran with `makepkg` (I personally prefer `makepkg -sirc`), will download the 0.2.0 release of MControlCenter and set up a package from it.
Since I am directly using binaries, the name of the package is **mcontrolcenter-bin**, in order to respect the [AUR submission guidelines](https://wiki.archlinux.org/title/AUR_submission_guidelines).

***Unfortunately***, I will not have the time to maintain this package on the AUR, thus why I am instead inserting it in a pull request. The idea is that the PKGBUILD stays on the repository until someone is available to maintain it on the AUR.

Finally, since this is my first time making a PKGBUILD, **I'd highly recommend you test it yourself** (using the live image of an Arch-based distribution for example). I've made sure to follow as closely as possible the installation script you provided, and the resulting package does seem to be working, but it's possible I've missed some quirks, dependencies, etc. **DO NOT MERGE** until either you or someone else also confirms the program works properly when installed like this.

### CODE REVIEW

**Comment by JordanViknar** [comment]
I'm not certain I filled the *provides* field correctly. Wait before possibly merging.

**Comment by JordanViknar** [comment]
> I may have filled the _provides_ field incorrectly, by forgetting to put _mcontrolcenter-helper_. Wait before possibly merging.

On second thought, I don't think it's necessary.

**Comment by JordanViknar** [comment]
Looks like an update of the PKGBUILD is gonna be needed for 0.3.0.

**Comment by JordanViknar** [comment]
Updated to 0.3.1

**Comment by JordanViknar** [comment]
Oops, I was busy these last few weeks, and didn't notice you updated MControlCenter.
Gonna update the "AUR" package right now.

**Comment by JordanViknar** [comment]
Nobody seems to be maintaining this package on the AUR, so I think I should just upload it myself.
You don't update extremely often anyways, so it won't be hard to maintain.

**Comment by joeg1484** [comment]
I have a MSI GP66 Vector and would love to test this out. Let me know when you get it into AUR or if you could direct me to the PKGBUILD file.

One thing... I saw this in modinfo about the ec_sys and wondered if I should worry...

parm:           write_support:Dangerous, reboot and removal of battery may be needed. (bool)

**Comment by JordanViknar** [comment]
> I have a MSI GP66 Vector and would love to test this out on Arch (EndeavorOS) . Let me know when you get it into AUR or if you could direct me to the PKGBUILD file.
> 
> One thing... I saw this in modinfo about the ec_sys and wondered if I should worry...
> 
> parm: write_support:Dangerous, reboot and removal of battery may be needed. (bool)

I may end up changing my mind and maintain it myself on the AUR, but I'd prefer for the PKGBUILD to be maintaned on the AUR by someone else. I am a student, and I could easily get very busy at a moment where an update would be required.

As for the PKGBUILD itself, it can be found in the "Files Changed" tab.
You can also check the scripts/aur-bin-pkgbuild path in my branch of the project to find the PKGBUILD.

**Comment by teackot** [comment]
Hello, I puplished the app to AUR and can maintain it.

I didn't see your PR, so I created the PKGBUILD file myself, but just so you know, your PKGBUILD probably works

**Comment by JordanViknar** [comment]
> Hello, I puplished the app to AUR and can maintain it.
> 
> I didn't see your PR, so I created the PKGBUILD file myself, but just so you know, your PKGBUILD probably works

Amazing. Well, I think this pull request can be safely closed.
Thank you for your work.

Seems like even if you did use my PKGBUILD as base, yours has some improvements over mine. Nice work.

**Pull request closed without merging**
